# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W22DJ3duL7qDL8Stb6fiFPEz2UdPoPwS
"""

def Numbers(MyNum):
    while MyNum!=101:
      MyNum = MyNum + 1

      if (MyNum % 3 == 0):
        print("Fizz")

      elif(MyNum % 5 == 0):
        print("Buzz")

      else:
        print("FizzBuzz")
        """
        it was bad interview  :xD)
        lame
        """
    
Numbers(1)
